environment         = "staging"
project_id          = "blakjaks-production"
region              = "us-central1"
gke_cluster_name    = "blakjaks-primary"
db_instance_name    = "blakjaks-postgres"
db_name             = "blakjaks_staging"
db_user             = "blakjaks_staging_user"
redis_instance_name = "blakjaks-redis"
