"""Add sequence column to messages for message ordering and replay

Revision ID: 027
Revises: 026
Create Date: 2026-03-03

The sequence column stores a per-channel monotonic integer generated by
Redis INCR. It is nullable for backwards compatibility — existing messages
will have sequence = NULL. The composite index on (channel_id, sequence)
supports efficient resume queries.
"""

from alembic import op
import sqlalchemy as sa

revision = "027"
down_revision = "026"
branch_labels = None
depends_on = None


def upgrade():
    # Add nullable sequence column — non-locking ADD COLUMN on PostgreSQL
    op.add_column("messages", sa.Column("sequence", sa.BigInteger(), nullable=True))

    # Create composite index for efficient resume queries.
    # Using op.create_index instead of CREATE INDEX CONCURRENTLY
    # because Alembic runs inside a transaction by default.
    op.create_index(
        "ix_messages_channel_sequence",
        "messages",
        ["channel_id", "sequence"],
    )


def downgrade():
    op.drop_index("ix_messages_channel_sequence", table_name="messages")
    op.drop_column("messages", "sequence")
